SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On
SecAuditEngine RelevantOnly
SecAuditLogType Serial
SecAuditLog /var/log/apache2/modsec_audit.log
SecRule ARGS "@rx <script" "id:1001,phase:2,block,log"